# frozen_string_literal: true

require 'minitest/test_task'
require 'rubocop/rake_task'

Minitest::TestTask.create do |t|
  t.test_globs = %w[**/*_test.rb]
end
RuboCop::RakeTask.new

task default: %i[test rubocop]
